scrape_configs:
  - job_name: "zipkin"
    scrape_interval: 5s
    metrics_path: "/prometheus"
    static_configs:
      - targets: ["192.168.100.11:9411"]
    metric_relabel_configs:
      # Response code count
      - source_labels: [__name__]
        regex: '^status_(\d+)_(.*)$'
        replacement: "${1}"
        target_label: status
      - source_labels: [__name__]
        regex: '^status_(\d+)_(.*)$'
        replacement: "${2}"
        target_label: path
      - source_labels: [__name__]
        regex: '^status_(\d+)_(.*)$'
        replacement: "http_requests_total"
        target_label: __name__
